[package]
name = "filter-parser"
version = "0.33.5"
edition = "2021"
description = "The parser for the Meilisearch filter syntax"
publish = false

[dependencies]
nom = "7.1.0"
nom_locate = "4.0.0"

[dev-dependencies]
insta = "1.18.2"
