[package]
name = "milli"
version = "0.1.0"
authors = ["Kerollmops <clement@meilisearch.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
bstr = "0.2.15"
byteorder = "1.4.2"
chrono = { version = "0.4.19", features = ["serde"] }
crossbeam-channel = "0.5.0"
csv = "1.1.5"
either = "1.6.1"
flate2 = "1.0.20"
fst = "0.4.5"
fxhash = "0.2.1"
grenad = { git = "https://github.com/Kerollmops/grenad.git", rev = "3adcb26" }
heed = { version = "0.10.6", default-features = false, features = ["lmdb", "sync-read-txn"] }
human_format = "1.0.3"
levenshtein_automata = { version = "0.2.0", features = ["fst_automaton"] }
linked-hash-map = "0.5.4"
meilisearch-tokenizer = { git = "https://github.com/meilisearch/Tokenizer.git", tag = "v0.2.0" }
memmap = "0.7.0"
num-traits = "0.2.14"
obkv = "0.1.1"
once_cell = "1.5.2"
ordered-float = "2.1.1"
rayon = "1.5.0"
regex = "1.4.3"
roaring = "0.6.5"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = { version = "1.0.62", features = ["preserve_order"] }
slice-group-by = "0.2.6"
smallstr =  { version = "0.2.0", features = ["serde"] }
smallvec = "1.6.1"
tempfile = "3.2.0"
uuid = { version = "0.8.2", features = ["v4"] }

# facet filter parser
pest = { git = "https://github.com/pest-parser/pest.git", rev = "51fd1d49f1041f7839975664ef71fe15c7dcaf67" }
pest_derive = "2.1.0"

# documents words self-join
itertools = "0.10.0"

# logging
log = "0.4.14"
logging_timer = "1.0.0"

# We temporarily depend on this crate just to fix this issue
# https://github.com/bheisler/TinyTemplate/pull/17
tinytemplate = "=1.1.0"

[dev-dependencies]
criterion = "0.3.4"
maplit = "1.0.2"
rand = "0.8.3"

[build-dependencies]
fst = "0.4.5"

[features]
default = []

[[bench]]
name = "search"
harness = false
