[package]
name = "benchmarks"
version = "0.32.0"
edition = "2018"
publish = false

[dependencies]
milli = { path = "../milli" }
anyhow = "1.0.56"
serde_json = { version = "1.0.79", features = ["preserve_order"] }
csv = "1.1.6"

[target.'cfg(target_os = "linux")'.dependencies]
jemallocator = "0.3.2"

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
roaring = "0.9.0"

[build-dependencies]
anyhow = "1.0.56"
bytes = "1.1.0"
flate2 = "1.0.22"
convert_case = "0.5.0"
reqwest = { version = "0.11.9", features = ["blocking", "rustls-tls"], default-features = false }

[[bench]]
name = "search_songs"
harness = false

[[bench]]
name = "search_wiki"
harness = false

[[bench]]
name = "search_geo"
harness = false

[[bench]]
name = "indexing"
harness = false

[[bench]]
name = "formatting"
harness = false
