[package]
name = "benchmarks"
version = "0.33.6"
edition = "2018"
publish = false

[dependencies]
anyhow = "1.0.56"
csv = "1.1.6"
milli = { path = "../milli" }
mimalloc = { version = "0.1.29", default-features = false }
serde_json = { version = "1.0.79", features = ["preserve_order"] }

[dev-dependencies]
criterion = { version = "0.3.5", features = ["html_reports"] }
rand = "0.8.5"
rand_chacha = "0.3.1"
roaring = "0.9.0"

[build-dependencies]
anyhow = "1.0.56"
bytes = "1.1.0"
convert_case = "0.5.0"
flate2 = "1.0.22"
reqwest = { version = "0.11.9", features = ["blocking", "rustls-tls"], default-features = false }

[[bench]]
name = "search_songs"
harness = false

[[bench]]
name = "search_wiki"
harness = false

[[bench]]
name = "search_geo"
harness = false

[[bench]]
name = "indexing"
harness = false

[[bench]]
name = "formatting"
harness = false
